### ISSUE TITLE
[PE-D][Tester E] Importing timetable resets semester to "semester 1"

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-3/tp#183]
![image.png](https://raw.githubusercontent.com/redders7/ped/main/files/0dd4a632-315d-47b8-bb6f-ba13ddfcffb4.png)

When importing a timetable in semester 2, the timetable is instead imported to semester 1. The semester is also automatically set to semester 1.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: redders7/ped#9

**Comment by kohnh** [comment]
The import function will switch the current semester to the semester indicated in the link as it is meant for you to see the timetable that you have just imported.  Why import a timetable and not want to make any changes to it? We do not want to hassle the user to have to change semesters in order to edit their imported timetable.  Will indicate this in the DG.
